name: Update APT Repo Index

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'debs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages.gz in debs folder
        run: |
          cd debs
          dpkg-scanpackages . /dev/null > Packages
          gzip -k Packages
          cd ..

      - name: Commit and Push Index
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add debs/Packages debs/Packages.gz
          git commit -m "Auto-update repo index" || echo "No changes to commit"
          git push origin HEAD:main
